import {
  Route as RootRoute,
  IndexRoute,
  AboutRoute,
  BillingParentRoute,
  BillingIndexRoute,
  BillingLoginRoute,
  BillingSignupRoute,
  BillingForgotPasswordRoute,
  BillingResetPasswordRoute,
  BillingSubscriptionRoute,
  BillingInvoicesRoute,
  BillingInvoiceDetailRoute,
  BillingPaymentsRoute,
  BillingPaymentDetailRoute,
  BillingPaypalRoute,
  BillingSettingsRoute,
  BillingSuccessRoute,
  BillingCancelRoute,
  BillingNotFoundRoute,
  NotFoundRoute,
} from './__root'

export {
  BillingIndexRoute,
  BillingLoginRoute,
  BillingSignupRoute,
  BillingForgotPasswordRoute,
  BillingResetPasswordRoute,
  BillingSubscriptionRoute,
  BillingInvoicesRoute,
  BillingInvoiceDetailRoute,
  BillingPaymentsRoute,
  BillingPaymentDetailRoute,
  BillingPaypalRoute,
  BillingSettingsRoute,
  BillingSuccessRoute,
  BillingCancelRoute,
  BillingNotFoundRoute,
  NotFoundRoute,
}

export const routeTree = RootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  BillingParentRoute.addChildren([
    BillingIndexRoute,
    BillingSubscriptionRoute,
    BillingInvoicesRoute,
    BillingInvoiceDetailRoute,
    BillingPaymentsRoute,
    BillingPaymentDetailRoute,
    BillingPaypalRoute,
    BillingSettingsRoute,
    BillingSuccessRoute,
    BillingCancelRoute,
    BillingNotFoundRoute,
  ]),
  BillingLoginRoute,
  BillingSignupRoute,
  BillingForgotPasswordRoute,
  BillingResetPasswordRoute,
  NotFoundRoute,
])